DROP DATABASE IF EXISTS restaurant_db;
CREATE DATABASE restaurant_db;
USE restaurant_db;

INSERT INTO customers (name,street,exterior,interior,zipCode,province,city,state,email,phoneNumber,createdAt,updatedAt) VALUES ('Francisco Silva','Viveros','123','123','03000','Mexico','Mexico','Distrito Federal','test@gmail.com','5555555555',sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopa de Fideo","comida","entrada1",20,"test images/sopa-de-fideos-a-los-tres-chiles.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("ConsomÈ de pollo","comida","entrada2",20,"test images/ConsomÈ-de-pollo-para-dieta-640x427.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Crema de verduras","comida","entrada3",20,"test images/receta-de-crema-de-verduras-al-curry-655x368.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Lentejas","comida","entrada4",20,"test images/receta-facil-de-sopa-de-lentejas-con-tocino.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Arroz a la mexicana","comida","guarnicion1",20,"test images/Arroz_a_la_Mexicana_Recipes_800x800.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Spaguetti rojo","comida","guarnicion2",20,"test images/spaguetti_rojo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de Lechuga","comida","guarnicion3",20,"test images/5600-2-ensalada-de-lechugas-variadas-pepino-y-tomates-cherry-xl-668x400x80xX.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Frijoles charros","comida","guarnicion4",20,"test images/frijoles-charros-1-1024x714.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Albondigas de res","comida","platillo1",30,"test images/albondigas-de-res-en-salsa-de-tomate-y-chipotle-video-e1562345363262.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortitas de pollo","comida","platillo2",30,"test images/tortitas-de-poro-con-pollo-566x440.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pescado empanizado","comida","platillo3",40,"test images/pescado_empanizado_con_amaranto.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Alambre de champiÒones","comida","platillo4",40,"test images/alambre de champiÒones.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Fresas con Crema","comida","postre1",15,"test images/fresas-con-crema-batida-y-merengue.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pay de limÛn","comida","postre2",15,"test images/carlota de limon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Gelatina","comida","postre3",15,"test images/gelatina-con-tutti-frutti.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tapioca","comida","postre4",15,"test images/tapioca.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de jamaica","comida","bebida1",7,"test images/agua_jamaica.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de limÛn","comida","bebida2",7,"test images/comohaceraguadelimon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de horchata","comida","bebida3",7,"test images/agua-horchata.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de tamarindo","comida","bebida4",7,"test images/agua-de-tamarindo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan","comida","complemento1",0,"test images/pan_blanco.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortillas","comida","complemento2",0,"test images/tortillas_de_maiz.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Cubiertos","comida","complemento3",0,"test images/Cubiertos.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("LimÛn","comida","complemento4",0,"test images/limon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopa de Fideo","vegetariana","entrada1",20,"test images/sopa-de-fideos-a-los-tres-chiles.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Lentejas","vegetariana","entrada2",20,"test images/receta-facil-de-sopa-de-lentejas-con-tocino.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Arroz a la mexicana","vegetariana","guarnicion1",20,"test images/Arroz_a_la_Mexicana_Recipes_800x800.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Spaguetti rojo","vegetariana","guarnicion2",20,"test images/spaguetti_rojo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de Lechuga","vegetariana","guarnicion3",20,"test images/5600-2-ensalada-de-lechugas-variadas-pepino-y-tomates-cherry-xl-668x400x80xX.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Alambre de champiÒones","vegetariana","platillo1",40,"test images/alambre de champiÒones.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Gelatina","vegetariana","postre1",15,"test images/gelatina-con-tutti-frutti.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tapioca","vegetariana","postre2",15,"test images/tapioca.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de jamaica","vegetariana","bebida1",7,"test images/agua_jamaica.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de limÛn","vegetariana","bebida2",7,"test images/comohaceraguadelimon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de horchata","vegetariana","bebida3",7,"test images/agua-horchata.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de tamarindo","vegetariana","bebida4",7,"test images/agua-de-tamarindo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan","vegetariana","complemento1",0,"test images/pan_blanco.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortillas","vegetariana","complemento2",0,"test images/tortillas_de_maiz.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Cubiertos","vegetariana","complemento3",0,"test images/Cubiertos.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("LimÛn","vegetariana","complemento4",0,"test images/limon.jpg",sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("En Proceso",1,sysdate(),sysdate());
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,1);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,2);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,3);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,4);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,5);
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Chilaquiles","desayuno","platillo1",50,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopes","desayuno","platillo2",20,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de yogurt","desayuno","platillo3",35,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Hot Cakes","desayuno","platillo4",60,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan Francés","desayuno","platillo5",60,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Café","desayuno","bebida1",15,"null",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Jugo de naranja","desayuno","bebida2",15,"null",sysdate(),sysdate());
commit;